name: test
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Check environment
        run: env
      - name: Test mkmacvm
        run: "$GITHUB_WORKSPACE/test"
        env:
          PARALLELS_KEY: ${{ secrets.PARALLELS_KEY }}
