name: test
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Run the mkmacvm script
        run: sudo "$GITHUB_WORKSPACE/mkmacvm"
