name: test
on:
  workflow_dispatch:
  pull_request:
concurrency: uses-parallels-key
jobs:
  #   run:
  #     runs-on: macos-12
  #     steps:
  #       - uses: actions/checkout@v3.0.2
  #       - name: test mkmacvm
  #         run: "$GITHUB_WORKSPACE/test"
  #         env:
  #           PARALLELS_KEY: ${{ secrets.PARALLELS_KEY }}
  #       - name: revoke key
  #         if: always()
  #         run: |
  #           if [ -e /usr/local/bin/prlsrvctl ]; then
  #             /usr/local/bin/prlsrvctl deactivate-license \
  #             || echo The license may have already been deactivated.
  #          fi
  debug:
    # if: failure()
    # needs: run
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3.0.2
      - name: enable SSH
        run: |
          sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
          brew install ngrok/ngrok/ngrok --no-quarantine
          ngrok tcp --authtoken "$NGROK_TOKEN" --log stdout --log-format logfmt 22 &
          mkdir -p "$HOME/.ssh"
          ssh-keygen -t rsa -f "$HOME/.ssh/id_rsa"
          cat "$HOME/.ssh/id_rsa.pub" >> "$HOME/.ssh/authorized_keys"
          chmod 0600 "$HOME/.ssh/"*
          chmod 0700 "$HOME/.ssh"
          echo SSH configured. Download connection script from Artifacts.
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      - name: test mkmacvm in debug mode
        run: "$GITHUB_WORKSPACE/test"
        env:
          PARALLELS_KEY: ${{ secrets.PARALLELS_KEY}}
          DEBUG: y
      - name: deactivate Parallels Desktop
        if: always()
        run: |
          if [ -e /usr/local/bin/prlsrvctl ]; then
            if ! output="$(/usr/local/bin/prlsrvctl deactivate-license 2>&1)"; then
              if ! echo "$output" | grep 'activation key is invalid' >/dev/null; then
                error="$output"
                error="$error\nYou may be able to deactivate Parallels Desktop at"
                error="$error\nhttps://my.parallels.com""
                echo "$error" >&2
                exit 1
              else
                echo "Unable to deactivate license; Parallels Desktop is already deactivated"
              fi
            else
              echo "$output"
            fi
          else
            error="Unable to deactivate Parallels Desktop: prlsrvctl not found" >&2
            error="$error\nYou may be able to deactivate Parallels Desktop at"
            error="$error\nhttps://my.parallels.com""
            echo "$error" >&2
            exit 1
          fi
      - name: take desktop screenshot
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        if: always()
        with:
          file-name: "desktop.jpg"
